dataset_name: CASIA
num_classes: 6
class_mapping:
  0: Neutral
  1: Happy
  2: Angry
  3: Sad
  4: Surprise
  5: Fear
paths:
  metadata_dir: ser_lib/data/dataset_configs/casia
  data_root_dir: data/CASIA
data_lists:
  train: train.jsonl
  val: val.jsonl
  test: test.jsonl
audio:
  target_sr: 16000
  max_duration: 5.0
transforms:
  train:
  - type: AddNoise
    snr: 15
  val:
  - type: Normalize
  test:
  - type: Normalize
