dataset_name: CASIA
num_classes: 6
class_mapping:
  0:
    en: Neutral
    zh: 平静
  1:
    en: Happy
    zh: 高兴
  2:
    en: Angry
    zh: 愤怒
  3:
    en: Sad
    zh: 悲伤
  4:
    en: Surprise
    zh: 惊吓
  5:
    en: Fear
    zh: 恐惧
paths:
  metadata_dir: ser_lib/dataset/configs/casia
  data_root_dir: data/CASIA
data_lists:
  train: train.jsonl
  val: val.jsonl
  test: test.jsonl
audio:
  target_sr: 16000
audio_processing:
  strategy: truncate_pad
  max_frames: 300
  window_size: 300
  stride: 150
features:
  log_mel:
    type: LogMelSpectrogram
    sample_rate: 16000
    n_fft: 1024
    hop_length: 256
    n_mels: 80
    f_min: 0.0
    f_max: 8000.0
    power: 2.0
    top_db: 80.0
transforms:
  waveform_level:
    train: []
    val: []
    test: []
  advanced_waveform_level:
    train: []
  spectrogram_level:
    train: []
    val: []
    test: []
  batch_level:
    train: []
